export const exampleConstant = () => [
  {
    constant: true,
    inputs: [],
    name: "SOME_VALUE",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
]

export const exampleAbi = () => [
  {
    constant: false,
    inputs: [],
    name: "countupForEther",
    outputs: [],
    payable: true,
    stateMutability: "payable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "someAddress",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "", type: "uint8" }, { name: "", type: "uint8" }, { name: "ret", type: "uint256" }],
    name: "twoUnnamedArgs",
    outputs: [{ name: "", type: "uint256" }],
    payable: true,
    stateMutability: "payable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "counter",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "", type: "uint256" }],
    name: "counterArray",
    outputs: [{ name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "offset", type: "uint256" }],
    name: "countup",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "returnAll",
    outputs: [{ name: "", type: "uint256" }, { name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "SOME_VALUE",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "offset", type: "uint256" }],
    name: "counterWithOffset",
    outputs: [{ name: "sum", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], payable: false, stateMutability: "nonpayable", type: "constructor" },
];
